app:
  cors:
    allowedOrigins: http://localhost:3000, https://ddt-jobsgo.vercel.app, http://your-personal-domain.com


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimthang.2612@gmail.com
    password: Kimthang1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://mydb.c3i48cu0ux6o.ap-southeast-1.rds.amazonaws.com:3306/jobsgo?createDatabaseIfNotExist=true
    username: admin
    password: kimthang1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 day